config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor' # mount this first, otherwise rails admin can't access
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  
  
  devise_scope :user do
    get     '/sign_in',     to: 'devise/sessions#new',        as: :sign_in
    delete  '/sign_out',    to: 'devise/sessions#destroy',    as: :sign_out
    get     'settings/:id', to: 'devise/registrations#edit',  as: :settings
  end

  devise_for :users, path: "", path_names: { sign_in: 'sign_in', sign_out: 'sign_out', edit: 'settings' }
  
  resources :communities
  resources :services
  resources :profiles
  
  resources :locations do
    resources :location_mentorships
    resources :companies
    resources :pricings
  end

  resources :users
  resources :news
  resources :events
  resources :mentors
  resources :enquiries

  #static
  root to: 'static_pages#landing'
  get '/about_us', to: 'static_pages#about_us', as: :about_us
  get '/join_us', to: 'static_pages#join_us', as: :join_us
  match "/magazine" => redirect('http://blog.jointhe.co'), :as => :magazine, via: [:get]
  match "/facebook" => redirect('http://facebook.com/thecokl'), :as => :facebook, via: [:get]
  match "/twitter" => redirect('http://twitter.com/thecokl'), :as => :twitter, via: [:get]
  match "/instagram" => redirect('http://instagram.com/thecokl'), :as => :instagram, via: [:get]
end

app/views/shared/_default_footer.html.slim
.footer-bg
  .container
    .row
      .col-sm-6
        .row
          .col-sm-4
            h4 Company
            span.footer-links = link_to "About us", about_us_path
            span.footer-links = link_to "Locations", locations_path
          .col-sm-4
            h4 Jointhe.co
            span.footer-links = link_to "Services", services_path
            span.footer-links = link_to "Events", events_path
            span.footer-links = link_to "Locations", locations_path
            span.footer-links = link_to "Mentors", profiles_path
            span.footer-links Bangsar.MY
            span.footer-links Doraisamy.MY
            span.footer-links HighSt.SG
          .col-sm-4
            h4 Follow us
            span.footer-links = link_to "Twitter", twitter_path
            span.footer-links = link_to "Facebook", facebook_path
            span.footer-links = link_to "Instagram", instagram_path
      .col-sm-6.col-md-push-1
        form.form-horizontal
          .form-group
            h4 Get updates
            h5 Stay up to date with what is going on with the co
            .row
              .col-sm-8
                input.form-control.input-lg placeholder="keyser.soze@gmail.com" type="email"
              .col-sm-4
                button.btn.btn-primary.btn-lg.btn-block type="submit"  Subscribe
    .row
      .col-md-12.padding-top
        .text-center
          span.footer-links copyright 2014. Terms &amp; Conditions Apply.

app/views/shared/_footer.html.slim
- if content_for? :footer
  = yield :footer
- else
  = render "shared/default_footer"

app/views/shared/_main_nav.html.slim
.navbar-wrapper
  nav.navbar.navbar-default.navbar-static-top
    .container
      .navbar-header
        button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to image_tag("theco-logo_white.png"), root_path, class: 'navbar-brand'
      #navbar.navbar-collapse.collapse
        
        ul.nav.navbar-nav.navbar-right
          li
            = link_to "Services", services_path
          li
            = link_to "Community", communities_path
          li
            = link_to "Events", events_path
          li
            = link_to "Locations", locations_path
          li
            = link_to "Magazine", magazine_path

app/views/shared/_nav.html.slim
- if content_for? :nav
  = yield :nav
- else
  = render "shared/main_nav"