config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor' # mount this first, otherwise rails admin can't access
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  
  
  devise_scope :user do
    get     '/sign_in',     to: 'devise/sessions#new',        as: :sign_in
    delete  '/sign_out',    to: 'devise/sessions#destroy',    as: :sign_out
    get     'settings/:id', to: 'devise/registrations#edit',  as: :settings
  end

  devise_for :users, path: "", path_names: { sign_in: 'sign_in', sign_out: 'sign_out', edit: 'settings' }
  
  resources :communities
  resources :services
  resources :profiles
  
  resources :locations do
    resources :location_mentorships
    resources :companies
    resources :pricings
  end

  resources :users
  resources :news
  resources :events
  resources :mentors
  resources :enquiries

  #static
  root to: 'static_pages#landing'
  get '/about_us', to: 'static_pages#about_us', as: :about_us
  get '/join_us', to: 'static_pages#join_us', as: :join_us
  match "/magazine" => redirect('http://blog.jointhe.co'), :as => :magazine, via: [:get]
  match "/facebook" => redirect('http://facebook.com/thecokl'), :as => :facebook, via: [:get]
  match "/twitter" => redirect('http://twitter.com/thecokl'), :as => :twitter, via: [:get]
  match "/instagram" => redirect('http://instagram.com/thecokl'), :as => :instagram, via: [:get]
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id                  :integer          not null, primary key
#  name                :string(255)      not null
#  created_at          :datetime
#  updated_at          :datetime
#  image               :string(255)
#  address             :text
#  description         :text
#  service_title       :string(255)      default("Our services")
#  service_description :text
#  mentor_title        :string(255)      default("Mentorship")
#  mentor_description  :text
#  company_title       :string(255)      default("Our companies")
#  company_description :text
#  map_title           :string(255)      default("Finding us")
#  map_description     :text
#  map_embed           :text
#  latitude            :float
#  longitude           :float
#  google_map_link     :string(255)
#  city_id             :integer
#

class Location < ActiveRecord::Base
  has_many :users

  has_many :available_pricings
  has_many :pricings, through: :available_pricings

  has_many :location_mentorships
  has_many :profiles, through: :location_mentorships
  
  has_many :available_services
  has_many :services, through: :available_services
  
  has_many :companies, dependent: :destroy
  has_many :events, dependent: :destroy

  has_many :available_areas
  has_many :areas, through: :available_areas

  validates :name, :city, presence: true
  mount_uploader :image, ImageUploader
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  belongs_to :city
  validates_associated :city

end

app/controllers/locations_controller.rb
class LocationsController < AdminController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_admin!, except: [:show, :index]
  before_action :find_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.create(location_params)
    set_flash @location.valid?
    redirect_or_render @location.valid?
  end

  def show
    @services = @location.available_services.all
    @areas = @location.available_areas.all
    @events = @location.events.limit(3).order(created_at: :desc)
    starter_pricing = @location.available_pricings.joins(:pricing).order("pricings.price DESC").first
    @starter_pricing = "#{starter_pricing.pricing.currency} #{starter_pricing.pricing.price}"
    @pricings_top = @location.pricings.limit(3).order(price: :desc)
    @pricings_bottom = @location.pricings.limit(2).order(price: :asc)
    @locations = Location.where.not(id: @location.id).limit(3)
  end

  def edit
  end

  def update
    @location.update(location_params)
    set_flash @location.valid?
    respond_to do |format|
      format.html { redirect_or_render @location.valid? }
      format.js
    end
  end

  def destroy
    @location.destroy
    set_flash
    redirect_or_render
  end

  private

  def find_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(
      :name,
      :city,
      :address,
      :image,
      :description,
      :service_title,
      :service_description,
      :mentor_title,
      :mentor_description,
      :company_title,
      :company_description,
      :map_title,
      :map_description,
      :map_embed
    )
  end
end

app/helpers/locations_helper.rb
module LocationsHelper

end

app/views/locations/_empty_pallet.html.slim
.location-index
    .col-md-12
      .padding-top-5
        h4 more to come...

app/views/locations/_empty_tile.html.slim
.location-tile
  .empty-tile
    .vcenter
      h5 more to come...

app/views/locations/_join_us.html.slim
.col-sm-6.col-md-4
  .thumbnail
    h5 = location.name
    = link_to image_tag(location.image), location_path(location.id)
    .caption
      - location.pricings.each do |pricing|
        p
          = pricing.name
      = link_to "View Selection", join_us_path, class: "button btn btn-lg btn-primary btn-block"

app/views/locations/_nav.html.slim
.navbar-wrapper
  nav.navbar.navbar-default.navbar-static-top
    .container
        = link_to image_tag("theco-logo_white.png"), root_path, class: 'navbar-brand'
          
          

app/views/locations/_pallet.html.slim
.location-index
  .col-md-12
    h2 #{location_el.name}
  .col-md-4
    = image_tag location_el.image, class:"location-index-img"
  .col-md-6.padding-left
    .description #{location_el.description.html_safe}
    .vcenter
      .service-tiles
        - location_el.services.each do |el|
          = render "services/tile_index", service_el: el
      .service-cta
        = link_to "View", location_path(location_el.id), class: "btn btn-primary btn-lg btn-block"

app/views/locations/_strip.html.slim
.location-row-bg
  .container
    .row
      .vcenter
        - locations.each do |el|
          = render "locations/tile", location: el
        = render "locations/empty_tile"

app/views/locations/_tile.html.slim
.location-tile
  h5 = location.name
  . = link_to image_tag(location.image), location_path(location.id) 

app/views/locations/index.html.slim
= content_for :nav
  = render "nav"
.hero-image.hero-image-2
  .container
    .row
      .hero-text 
        span.headline #{City.all.size} countries
        span.headline.headline-underline #{Location.all.size} locations
        span.subheader In the heart of it all
.beige-row
  .container
    .row.padding-bottom
      .col-md-12
        - @locations.each do |el|
            = render "locations/pallet", location_el: el
        = render "locations/empty_pallet"

app/views/locations/show.html.slim
= content_for :nav
  = render "nav"
.hero-image.hero-image-2
  .container
    .row
      .hero-text 
        span.headline #{@location.name}
        span.headline.headline-underline #{@location.city.name}
        span.subheader a seat starts from #{@starter_pricing}
.white-row 
  .container
    .row.vcenter
      .col-md-5
        h4 
          strong = @location.address.html_safe
        = @location.map_description
      .col-md-2
        h4 
          strong = @location.phone
      .col-md-2
        button.btn.btn-lg.btn-primary Host an Event
      .col-md-2
        button.btn.btn-lg.btn-primary Get a seat
.beige-row
  .container
    .row.padding-bottom
      .col-md-4
        h3 Facilities
      .col-md-8
        .pull-right
          - @services.each do |el|
              = render "services/tile", service_el: el
    .row.padding-bottom
      - @areas.each do |el|
        = render "areas/tile", area_el: el
    .row.padding-bottom
      h3 Events
      .vcenter
        - @events.each do |el|
          = render "events/tile", event_el: el
        = render "events/empty_tile"

.beige-row
  .container
    h3.gray-text Our location
.row.padding-bottom style="background-image:url('#{@location.image}'); height: 415px;"

  / = link_to image_tag(@location.image), @location.google_map_link
.beige-row
  .container
    h3.gray-text We've got seats!
    .row
      - @pricings_top.each do |el|
        = render "pricings/tile", pricing: el
.beige-row
  .container
    .row
    - @pricings_bottom.each do |el|
      = render "pricings/pallet", pricing: el
  .row
    .text-center
      h4.gray-text Need a custom setup, enquire!
= render "locations/strip", locations: @locations
          